global:
  metrics_output_folder: "/home/yuanjian/tests/"
  large_file_output_folder: "/anvil/scratch/x-yliu4/tests"

datasets:
  - name: "Nyx 512"
    dimension: [512, 512, 512]
    fileNames: ["velocity_x.f32", "velocity_y.f32", "velocity_z.f32", "temperature.f32"]
    folder: "/anvil/projects/x-cis220161/datasets/NYX_512x512x512/SDRBENCH-EXASKY-NYX-512x512x512_log"
    ebs: [1e-1, 1e-2, 1e-3, 1e-4, 1e-5]

compressors:
  - name: "sz3 official"
    ext: ".sz3"
    executable: "/home/x-yliu4/sz3-yuanjian/official_sz3/SZ3/build/tools/sz3/sz3"
    compress_params: ["-f", "-i", "$fileName", "-z", "$compressedFileName", "-M", "ABS", "$eb"] # append dimension at the end e.g. -3 512 512 512
    decompress_params: ["-f", "-z", "$compressedFileName", "-o", "$decompressedFileName", "-M", "ABS", "$eb", "-a"] # append dimension at the end