global:
  metrics_output_folder: "/u/yliu4/tests"
  large_file_output_folder: "/projects/bcnl/yliu4/datasets/scratch"

datasets:
  - name: "Nyx-512"
    dimension: [512, 512, 512]
    ext: ".f32"
    fileNames: ["velocity_x.f32", "velocity_y.f32", "velocity_z.f32", "temperature.f32"]
    folder: "/projects/bcnl/yliu4/datasets/NYX_512x512x512/SDRBENCH-EXASKY-NYX-512x512x512_log"
    ebs: [1e-1, 1e-3, 1e-5]
  - name: "CESM-1800x3600"
    dimension: [1800, 3600]
    ext: ".dat"
    fileNames: ["CLDHGH_1_1800_3600.dat", "ODV_bcar1_1_1800_3600.dat", "SNOWHICE_1_1800_3600.dat"]
    folder: "/projects/bcnl/yliu4/datasets/CESM-ATM/SDRBENCH-CESM-ATM-cleared-1800x3600"
    ebs: [1e-1, 1e-3, 1e-5]
  - name: "Miranda"
    dimension: [384, 384, 256]
    ext: ".dat"
    fileNames: ["density.f32.dat", "diffusivity.f32.dat", "pressure.f32.dat", "velocityy.f32.dat", "velocityz.f32.dat"]
    folder: "/projects/bcnl/yliu4/datasets/Miranda"
    ebs: [1e-1, 1e-3, 1e-5]
  - name: "Hurricane-Isabel"
    dimension: [500, 500, 100]
    fileNames: ["CLOUDf48_log10.bin.dat", "QCLOUDf48_log10.bin.dat", "QICEf48_log10.bin.dat", "QSNOWf48_log10.bin.dat", "QRAINf48_log10.bin.dat"]
    ext: ".dat"
    folder: "/projects/bcnl/yliu4/datasets/Hurricane-ISABEL/logdata"
    ebs: [1e-1, 1e-3, 1e-5]


compressors:
  - name: "sz3-official"
    ext: ".sz3"
    executable: "/u/yliu4/SZ3/build/tools/sz3/sz3"
    compress_params: ["-f", "-i", "$fileName", "-z", "$compressedFileName", "-M", "ABS", "$eb"] # append dimension at the end e.g. -3 512 512 512
    decompress_params: ["-f", "-z", "$compressedFileName", "-o", "$decompressedFileName", "-M", "ABS", "$eb"] # append dimension at the end