name: NCSA-Delta
globus_compute_id: efe05548-fae9-4a83-8321-6f11938ab497
globus_transfer_id: 7e936164-de58-4e3d-85da-21aa23c07169
globus_client_id: 1fb9c8a9-1aff-4d46-9f37-e3b0d44194f2
work_dir: /u/yliu4/playground
defaults:
  dataset_dir: /projects/bcnl/yliu4/datasets/NYX/SDRBENCH-EXASKY-NYX-512x512x512_log
  sz3_exe: /u/yliu4/SZ3/build/tools/sz3/sz3